import { user } from "../DB";
import * as argon2 from "argon2";

interface Users {
  first_name: string;
  last_name: string;
  email: string;
  password: string;
  gender: string;
  avatar: string;
  domain: string;
  available: boolean;
}
/*
const users: Users[] = [
  {
    first_name: "Anet",
    last_name: "Doe",
    email: "adoe0@comcast.net",
    password: "adoe0@comcast.net",
    gender: "Female",
    avatar: "https://robohash.org/sintessequaerat.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },

  {
    first_name: "Honoria",
    last_name: "Caughte",
    email: "hcaughte1@google.com.br",
    password: "hcaughte1@google.com.br",
    gender: "Female",
    avatar:
      "https://robohash.org/temporibusporrolaboriosam.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Wiley",
    last_name: "Boarder",
    email: "wboarder2@xing.com",
    password: "wboarder2@xing.com",
    gender: "Male",
    avatar:
      "https://robohash.org/laboriosamdolorepossimus.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Brett",
    last_name: "Ivetts",
    email: "bivetts3@netlog.com",
    password: "bivetts3@netlog.com",
    gender: "Agender",
    avatar: "https://robohash.org/ullamsuntet.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Horst",
    last_name: "Grastye",
    email: "hgrastye4@dmoz.org",
    password: "hgrastye4@dmoz.org",
    gender: "Male",
    avatar: "https://robohash.org/utquirepudiandae.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Monique",
    last_name: "Wilbud",
    email: "mwilbud5@state.gov",
    password: "mwilbud5@state.gov",
    gender: "Female",
    avatar: "https://robohash.org/maximequiomnis.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Kalindi",
    last_name: "Vinson",
    email: "kvinson6@g.co",
    password: "kvinson6@g.co",
    gender: "Female",
    avatar: "https://robohash.org/occaecatinihilquos.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Janos",
    last_name: "Le Noire",
    email: "jlenoire7@sakura.ne.jp",
    password: "jlenoire7@sakura.ne.jp",
    gender: "Male",
    avatar:
      "https://robohash.org/praesentiumquasicorporis.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Corella",
    last_name: "Coniff",
    email: "cconiff8@guardian.co.uk",
    password: "cconiff8@guardian.co.uk",
    gender: "Bigender",
    avatar: "https://robohash.org/nihilexcepturiomnis.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Cecilia",
    last_name: "Waldocke",
    email: "cwaldocke9@gmpg.org",
    password: "cwaldocke9@gmpg.org",
    gender: "Female",
    avatar: "https://robohash.org/commodiestvoluptatem.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
];
*/
//----------------------------------
/*
const users: Users[] = [
  {
    first_name: "Suellen",
    last_name: "Bretton",
    email: "sbrettona@mapquest.com",
    password: "sbrettona@mapquest.com",
    gender: "Female",
    avatar: "https://robohash.org/cupiditatemaioresaut.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Deloris",
    last_name: "Evered",
    email: "deveredb@ovh.net",
    password: "deveredb@ovh.net",
    gender: "Female",
    avatar:
      "https://robohash.org/blanditiiscumqueimpedit.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Candice",
    last_name: "Harbar",
    email: "charbarc@home.pl",
    password: "charbarc@home.pl",
    gender: "Female",
    avatar: "https://robohash.org/autarchitectotenetur.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "John",
    last_name: "Fine",
    email: "jfined@facebook.com",
    password: "jfined@facebook.com",
    gender: "Male",
    avatar:
      "https://robohash.org/etvoluptatemoccaecati.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Gonzalo",
    last_name: "Tilliard",
    email: "gtilliarde@marketwatch.com",
    password: "gtilliarde@marketwatch.com",
    gender: "Agender",
    avatar:
      "https://robohash.org/voluptatemfacilisodit.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Hertha",
    last_name: "Sterrick",
    email: "hsterrickf@nationalgeographic.com",
    password: "hsterrickf@nationalgeographic.com",
    gender: "Female",
    avatar:
      "https://robohash.org/rerumoptiorepudiandae.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Benjamin",
    last_name: "Challiner",
    email: "bchallinerg@nydailynews.com",
    password: "bchallinerg@nydailynews.com",
    gender: "Male",
    avatar: "https://robohash.org/architectoomnisquia.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Lockwood",
    last_name: "Wermerling",
    email: "lwermerlingh@imgur.com",
    password: "lwermerlingh@imgur.com",
    gender: "Male",
    avatar: "https://robohash.org/cumquenoncommodi.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Baillie",
    last_name: "Mulqueeny",
    email: "bmulqueenyi@wikispaces.com",
    password: "bmulqueenyi@wikispaces.com",
    gender: "Male",
    avatar: "https://robohash.org/dolorumvelitquam.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Quintus",
    last_name: "Gibbieson",
    email: "qgibbiesonj@symantec.com",
    password: "qgibbiesonj@symantec.com",
    gender: "Male",
    avatar:
      "https://robohash.org/delectusconsectetursed.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Heinrik",
    last_name: "Brockbank",
    email: "hbrockbankk@plala.or.jp",
    password: "hbrockbankk@plala.or.jp",
    gender: "Male",
    avatar: "https://robohash.org/eumdelectusducimus.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Klara",
    last_name: "Lorking",
    email: "klorkingl@kickstarter.com",
    password: "klorkingl@kickstarter.com",
    gender: "Female",
    avatar: "https://robohash.org/veniamenimlaborum.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Lynelle",
    last_name: "Mawne",
    email: "lmawnem@nsw.gov.au",
    password: "lmawnem@nsw.gov.au",
    gender: "Female",
    avatar: "https://robohash.org/totamsuntrem.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Colver",
    last_name: "Mc Harg",
    email: "cmchargn@google.co.uk",
    password: "cmchargn@google.co.uk",
    gender: "Male",
    avatar: "https://robohash.org/voluptasipsaquam.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Tristam",
    last_name: "Morsley",
    email: "tmorsleyo@engadget.com",
    password: "tmorsleyo@engadget.com",
    gender: "Male",
    avatar:
      "https://robohash.org/repellendusetvoluptatibus.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Barnabe",
    last_name: "Cathrall",
    email: "bcathrallp@photobucket.com",
    password: "bcathrallp@photobucket.com",
    gender: "Polygender",
    avatar: "https://robohash.org/atnonqui.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Shauna",
    last_name: "Routham",
    email: "srouthamq@shutterfly.com",
    password: "srouthamq@shutterfly.com",
    gender: "Female",
    avatar: "https://robohash.org/doloresolutasuscipit.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Selena",
    last_name: "Mathewson",
    email: "smathewsonr@auda.org.au",
    password: "smathewsonr@auda.org.au",
    gender: "Female",
    avatar: "https://robohash.org/recusandaevelut.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Genny",
    last_name: "Kane",
    email: "gkanes@cocolog-nifty.com",
    password: "gkanes@cocolog-nifty.com",
    gender: "Female",
    avatar: "https://robohash.org/exteneturrepudiandae.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Iver",
    last_name: "Dansie",
    email: "idansiet@timesonline.co.uk",
    password: "idansiet@timesonline.co.uk",
    gender: "Male",
    avatar: "https://robohash.org/iddoloremquequidem.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Raff",
    last_name: "Shearme",
    email: "rshearmeu@histats.com",
    password: "rshearmeu@histats.com",
    gender: "Male",
    avatar: "https://robohash.org/doloresquidemet.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Grantley",
    last_name: "Gillam",
    email: "ggillamv@bizjournals.com",
    password: "ggillamv@bizjournals.com",
    gender: "Male",
    avatar: "https://robohash.org/earumminimaillo.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Tamas",
    last_name: "Lerego",
    email: "tleregow@g.co",
    password: "tleregow@g.co",
    gender: "Male",
    avatar: "https://robohash.org/utenimnisi.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Jacinda",
    last_name: "Giacobelli",
    email: "jgiacobellix@marriott.com",
    password: "jgiacobellix@marriott.com",
    gender: "Female",
    avatar: "https://robohash.org/ullametvoluptas.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Isadore",
    last_name: "Gorries",
    email: "igorriesy@ox.ac.uk",
    password: "igorriesy@ox.ac.uk",
    gender: "Non-binary",
    avatar: "https://robohash.org/etexercitationemeum.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Giovanni",
    last_name: "Choak",
    email: "gchoakz@abc.net.au",
    password: "gchoakz@abc.net.au",
    gender: "Male",
    avatar: "https://robohash.org/autemeumautem.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Miof mela",
    last_name: "Rummin",
    email: "mrummin10@usa.gov",
    password: "mrummin10@usa.gov",
    gender: "Female",
    avatar:
      "https://robohash.org/voluptatemmaioreserror.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Zora",
    last_name: "Kew",
    email: "zkew11@toplist.cz",
    password: "zkew11@toplist.cz",
    gender: "Polygender",
    avatar: "https://robohash.org/utearumpossimus.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Pansie",
    last_name: "Liffey",
    email: "pliffey12@free.fr",
    password: "pliffey12@free.fr",
    gender: "Female",
    avatar: "https://robohash.org/quodeseruntearum.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Prentiss",
    last_name: "Dearing",
    email: "pdearing13@cam.ac.uk",
    password: "pdearing13@cam.ac.uk",
    gender: "Male",
    avatar: "https://robohash.org/laudantiumdoloreos.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Chick",
    last_name: "Louth",
    email: "clouth14@mayoclinic.com",
    password: "clouth14@mayoclinic.com",
    gender: "Male",
    avatar: "https://robohash.org/nihilsitest.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Alva",
    last_name: "Goozee",
    email: "agoozee15@google.es",
    password: "agoozee15@google.es",
    gender: "Male",
    avatar: "https://robohash.org/nonautofficiis.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Fields",
    last_name: "Zucker",
    email: "fzucker16@ucsd.edu",
    password: "fzucker16@ucsd.edu",
    gender: "Male",
    avatar:
      "https://robohash.org/quiainciduntconsequatur.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Bren",
    last_name: "Dilke",
    email: "bdilke17@virginia.edu",
    password: "bdilke17@virginia.edu",
    gender: "Male",
    avatar:
      "https://robohash.org/recusandaererumblanditiis.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Ernesta",
    last_name: "Parzizek",
    email: "eparzizek18@delicious.com",
    password: "eparzizek18@delicious.com",
    gender: "Female",
    avatar: "https://robohash.org/estharumdolor.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Symon",
    last_name: "Paniman",
    email: "spaniman19@dion.ne.jp",
    password: "spaniman19@dion.ne.jp",
    gender: "Male",
    avatar:
      "https://robohash.org/consequaturharumdistinctio.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Donny",
    last_name: "Dibson",
    email: "ddibson1a@fc2.com",
    password: "ddibson1a@fc2.com",
    gender: "Male",
    avatar: "https://robohash.org/doloresautemdolore.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Nady",
    last_name: "Blondel",
    email: "nblondel1b@icq.com",
    password: "nblondel1b@icq.com",
    gender: "Female",
    avatar: "https://robohash.org/placeatrepellataut.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Sarina",
    last_name: "Picard",
    email: "spicard1c@t.co",
    password: "spicard1c@t.co",
    gender: "Female",
    avatar: "https://robohash.org/voluptassitexplicabo.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Lewie",
    last_name: "Szimon",
    email: "lszimon1d@constantcontact.com",
    password: "lszimon1d@constantcontact.com",
    gender: "Male",
    avatar: "https://robohash.org/etsapienteomnis.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Ricardo",
    last_name: "Mulford",
    email: "rmulford1e@xinhuanet.com",
    password: "rmulford1e@xinhuanet.com",
    gender: "Genderfluid",
    avatar:
      "https://robohash.org/dolorestemporibusaperiam.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Herc",
    last_name: "Lancett",
    email: "hlancett1f@engadget.com",
    password: "hlancett1f@engadget.com",
    gender: "Male",
    avatar: "https://robohash.org/inventorenonnisi.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Aldridge",
    last_name: "Echlin",
    email: "aechlin1g@apache.org",
    password: "aechlin1g@apache.org",
    gender: "Male",
    avatar:
      "https://robohash.org/voluptasrationecorrupti.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Harp",
    last_name: "Petz",
    email: "hpetz1h@discuz.net",
    password: "hpetz1h@discuz.net",
    gender: "Male",
    avatar:
      "https://robohash.org/distinctionumquamconsectetur.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Gypsy",
    last_name: "Ledgeway",
    email: "gledgeway1i@washington.edu",
    password: "gledgeway1i@washington.edu",
    gender: "Female",
    avatar: "https://robohash.org/quiautiste.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Blithe",
    last_name: "Kingsland",
    email: "bkingsland1j@imdb.com",
    password: "bkingsland1j@imdb.com",
    gender: "Female",
    avatar: "https://robohash.org/sedestsuscipit.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Lynn",
    last_name: "Besque",
    email: "lbesque1k@about.me",
    password: "lbesque1k@about.me",
    gender: "Genderqueer",
    avatar:
      "https://robohash.org/teneturofficiaconsequuntur.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Lothaire",
    last_name: "Olliffe",
    email: "lolliffe1l@sogou.com",
    password: "lolliffe1l@sogou.com",
    gender: "Male",
    avatar: "https://robohash.org/aliquamporroomnis.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Harmony",
    last_name: "Henzer",
    email: "hhenzer1m@surveymonkey.com",
    password: "hhenzer1m@surveymonkey.com",
    gender: "Female",
    avatar:
      "https://robohash.org/quaeaccusamusoccaecati.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Robinett",
    last_name: "Oolahan",
    email: "roolahan1n@globo.com",
    password: "roolahan1n@globo.com",
    gender: "Female",
    avatar: "https://robohash.org/estestquia.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Perri",
    last_name: "Molines",
    email: "pmolines1o@dell.com",
    password: "pmolines1o@dell.com",
    gender: "Female",
    avatar: "https://robohash.org/odioculpaaccusamus.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Donia",
    last_name: "Fonso",
    email: "dfonso1p@youku.com",
    password: "dfonso1p@youku.com",
    gender: "Female",
    avatar: "https://robohash.org/fugaetdelectus.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Hiram",
    last_name: "Entwistle",
    email: "hentwistle1q@ebay.com",
    password: "hentwistle1q@ebay.com",
    gender: "Male",
    avatar: "https://robohash.org/laboriosamomnisodit.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Dasie",
    last_name: "French",
    email: "dfrench1r@oakley.com",
    password: "dfrench1r@oakley.com",
    gender: "Female",
    avatar: "https://robohash.org/namtemporatempore.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Terencio",
    last_name: "Strephan",
    email: "tstrephan1s@adobe.com",
    password: "tstrephan1s@adobe.com",
    gender: "Male",
    avatar: "https://robohash.org/idutcorporis.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Miquela",
    last_name: "Wybern",
    email: "mwybern1t@examiner.com",
    password: "mwybern1t@examiner.com",
    gender: "Female",
    avatar: "https://robohash.org/vitaesedipsam.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Wald",
    last_name: "McKinless",
    email: "wmckinless1u@stanford.edu",
    password: "wmckinless1u@stanford.edu",
    gender: "Male",
    avatar: "https://robohash.org/sintquiveritatis.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Giordano",
    last_name: "Heddan",
    email: "gheddan1v@t.co",
    password: "gheddan1v@t.co",
    gender: "Male",
    avatar: "https://robohash.org/nostrumsintatque.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Dominic",
    last_name: "Lumm",
    email: "dlumm1w@ifeng.com",
    password: "dlumm1w@ifeng.com",
    gender: "Male",
    avatar: "https://robohash.org/iddolorequis.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Connie",
    last_name: "Andreev",
    email: "candreev1x@omniture.com",
    password: "candreev1x@omniture.com",
    gender: "Female",
    avatar: "https://robohash.org/distinctioauteum.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Hedwiga",
    last_name: "Lumbers",
    email: "hlumbers1y@redcross.org",
    password: "hlumbers1y@redcross.org",
    gender: "Female",
    avatar: "https://robohash.org/maximeestnatus.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Petronella",
    last_name: "Bravington",
    email: "pbravington1z@accuweather.com",
    password: "pbravington1z@accuweather.com",
    gender: "Female",
    avatar: "https://robohash.org/voluptasmaioresnihil.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Somerset",
    last_name: "Dewerson",
    email: "sdewerson20@amazon.co.jp",
    password: "sdewerson20@amazon.co.jp",
    gender: "Male",
    avatar: "https://robohash.org/quisdebitisexcepturi.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Vassily",
    last_name: "Riping",
    email: "vriping21@umich.edu",
    password: "vriping21@umich.edu",
    gender: "Male",
    avatar: "https://robohash.org/natusundeperferendis.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Karlen",
    last_name: "Hastie",
    email: "khastie22@nasa.gov",
    password: "khastie22@nasa.gov",
    gender: "Female",
    avatar:
      "https://robohash.org/aliasreprehenderitsit.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Cori",
    last_name: "Tromans",
    email: "ctromans23@feedburner.com",
    password: "ctromans23@feedburner.com",
    gender: "Male",
    avatar: "https://robohash.org/omnisquaeratquae.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Lolly",
    last_name: "Steffens",
    email: "lsteffens24@elegantthemes.com",
    password: "lsteffens24@elegantthemes.com",
    gender: "Female",
    avatar: "https://robohash.org/quaecumquam.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Ricki",
    last_name: "Denisovich",
    email: "rdenisovich25@mediafire.com",
    password: "rdenisovich25@mediafire.com",
    gender: "Male",
    avatar: "https://robohash.org/istedelectusaliquam.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Devy",
    last_name: "Tregonna",
    email: "dtregonna26@globo.com",
    password: "dtregonna26@globo.com",
    gender: "Bigender",
    avatar: "https://robohash.org/etrationefuga.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Carry",
    last_name: "Harrie",
    email: "charrie27@ucoz.ru",
    password: "charrie27@ucoz.ru",
    gender: "Female",
    avatar: "https://robohash.org/suntverovoluptatem.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Curran",
    last_name: "Mea",
    email: "cmea28@cafepress.com",
    password: "cmea28@cafepress.com",
    gender: "Male",
    avatar: "https://robohash.org/officianobisomnis.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Nan",
    last_name: "Poxon",
    email: "npoxon29@live.com",
    password: "npoxon29@live.com",
    gender: "Female",
    avatar: "https://robohash.org/iureadipiscipossimus.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Tim",
    last_name: "Redford",
    email: "tredford2a@paginegialle.it",
    password: "tredford2a@paginegialle.it",
    gender: "Female",
    avatar: "https://robohash.org/magniametneque.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Orella",
    last_name: "Gibke",
    email: "ogibke2b@house.gov",
    password: "ogibke2b@house.gov",
    gender: "Female",
    avatar: "https://robohash.org/estliberoaspernatur.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Almeria",
    last_name: "Arr",
    email: "aarr2c@washington.edu",
    password: "aarr2c@washington.edu",
    gender: "Female",
    avatar: "https://robohash.org/temporavelitquis.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Robyn",
    last_name: "Landrick",
    email: "rlandrick2d@elegantthemes.com",
    password: "rlandrick2d@elegantthemes.com",
    gender: "Female",
    avatar:
      "https://robohash.org/architectoevenietquis.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Shermie",
    last_name: "Laux",
    email: "slaux2e@seattletimes.com",
    password: "slaux2e@seattletimes.com",
    gender: "Male",
    avatar: "https://robohash.org/veltemporibusitaque.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Brig",
    last_name: "Cuseick",
    email: "bcuseick2f@rakuten.co.jp",
    password: "bcuseick2f@rakuten.co.jp",
    gender: "Male",
    avatar:
      "https://robohash.org/voluptatemdignissimosomnis.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Crichton",
    last_name: "Ironmonger",
    email: "cironmonger2g@icq.com",
    password: "cironmonger2g@icq.com",
    gender: "Male",
    avatar: "https://robohash.org/etquoquisquam.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Falkner",
    last_name: "Hallet",
    email: "fhallet2h@cnn.com",
    password: "fhallet2h@cnn.com",
    gender: "Male",
    avatar: "https://robohash.org/evenietavoluptatem.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Ephrayim",
    last_name: "McCray",
    email: "emccray2i@prlog.org",
    password: "emccray2i@prlog.org",
    gender: "Male",
    avatar: "https://robohash.org/dolorsuscipitdolorum.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Lita",
    last_name: "Kedwell",
    email: "lkedwell2j@gizmodo.com",
    password: "lkedwell2j@gizmodo.com",
    gender: "Bigender",
    avatar:
      "https://robohash.org/perspiciatisomnisdolore.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Abbie",
    last_name: "Greenstock",
    email: "agreenstock2k@vinaora.com",
    password: "agreenstock2k@vinaora.com",
    gender: "Genderqueer",
    avatar: "https://robohash.org/namautlaudantium.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Jermaine",
    last_name: "Boorne",
    email: "jboorne2l@bravesites.com",
    password: "jboorne2l@bravesites.com",
    gender: "Female",
    avatar:
      "https://robohash.org/omnisaliquidreprehenderit.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Lilla",
    last_name: "Gensavage",
    email: "lgensavage2m@ihg.com",
    password: "lgensavage2m@ihg.com",
    gender: "Female",
    avatar: "https://robohash.org/etveritatismolestiae.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Marcelia",
    last_name: "Camillo",
    email: "mcamillo2n@who.int",
    password: "mcamillo2n@who.int",
    gender: "Female",
    avatar: "https://robohash.org/magnamvoluptasullam.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Liliane",
    last_name: "Bartul",
    email: "lbartul2o@arizona.edu",
    password: "lbartul2o@arizona.edu",
    gender: "Female",
    avatar: "https://robohash.org/illumquaeratmagni.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Ag",
    last_name: "Bettleson",
    email: "abettleson2p@nps.gov",
    password: "abettleson2p@nps.gov",
    gender: "Female",
    avatar: "https://robohash.org/utimpeditqui.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Garvin",
    last_name: "Rainsdon",
    email: "grainsdon2q@woothemes.com",
    password: "grainsdon2q@woothemes.com",
    gender: "Male",
    avatar: "https://robohash.org/placeatquiset.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
];
*/
// ---------------------------------
/*
const users: Users[] = [
  {
    first_name: "Ronalda",
    last_name: "Keir",
    email: "rkeir2r@ustream.tv",
    password: "rkeir2r@ustream.tv",
    gender: "Female",
    avatar: "https://robohash.org/ducimusoditvero.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Roxanna",
    last_name: "Skipton",
    email: "rskipton2s@constantcontact.com",
    password: "rskipton2s@constantcontact.com",
    gender: "Female",
    avatar: "https://robohash.org/ullamnobisquia.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Erinn",
    last_name: "Breeze",
    email: "ebreeze2t@miibeian.gov.cn",
    password: "ebreeze2t@miibeian.gov.cn",
    gender: "Genderqueer",
    avatar: "https://robohash.org/veritatisilloet.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Harcourt",
    last_name: "Wooffinden",
    email: "hwooffinden2u@yandex.ru",
    password: "hwooffinden2u@yandex.ru",
    gender: "Male",
    avatar: "https://robohash.org/maximeipsalibero.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Leigh",
    last_name: "Smithen",
    email: "lsmithen2v@tamu.edu",
    password: "lsmithen2v@tamu.edu",
    gender: "Female",
    avatar:
      "https://robohash.org/adipiscicorruptidebitis.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Court",
    last_name: "Arpur",
    email: "carpur2w@bigcartel.com",
    password: "carpur2w@bigcartel.com",
    gender: "Male",
    avatar: "https://robohash.org/namprovidenttenetur.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Nicolina",
    last_name: "Clutterbuck",
    email: "nclutterbuck2x@tumblr.com",
    password: "nclutterbuck2x@tumblr.com",
    gender: "Female",
    avatar: "https://robohash.org/asperioresnonnulla.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Sibby",
    last_name: "Barnsdale",
    email: "sbarnsdale2y@earthlink.net",
    password: "sbarnsdale2y@earthlink.net",
    gender: "Female",
    avatar: "https://robohash.org/atdoloribusimpedit.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Nichols",
    last_name: "Wisham",
    email: "nwisham2z@ovh.net",
    password: "nwisham2z@ovh.net",
    gender: "Male",
    avatar: "https://robohash.org/autemvelsint.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Stephenie",
    last_name: "Brocks",
    email: "sbrocks30@shareasale.com",
    password: "sbrocks30@shareasale.com",
    gender: "Female",
    avatar: "https://robohash.org/cuminet.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
];
*/

//  -----------

const users: Users[] = [
  {
    first_name: "Martynne",
    last_name: "Abrashkin",
    email: "mabrashkin31@tumblr.com",
    password: "mabrashkin31@tumblr.com",
    gender: "Female",
    avatar:
      "https://robohash.org/deseruntnumquamimpedit.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Leonanie",
    last_name: "Sullly",
    email: "lsullly32@nyu.edu",
    password: "lsullly32@nyu.edu",
    gender: "Female",
    avatar:
      "https://robohash.org/laudantiumipsadolores.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Matelda",
    last_name: "Josefsen",
    email: "mjosefsen33@mozilla.org",
    password: "mjosefsen33@mozilla.org",
    gender: "Female",
    avatar: "https://robohash.org/ullammaioresea.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Barron",
    last_name: "Treuge",
    email: "btreuge34@yahoo.co.jp",
    password: "btreuge34@yahoo.co.jp",
    gender: "Male",
    avatar: "https://robohash.org/velitutlaudantium.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Karlik",
    last_name: "Broggelli",
    email: "kbroggelli35@cargocollective.com",
    password: "kbroggelli35@cargocollective.com",
    gender: "Male",
    avatar:
      "https://robohash.org/voluptatesassumendaquisquam.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Norene",
    last_name: "Comer",
    email: "ncomer36@ustream.tv",
    password: "ncomer36@ustream.tv",
    gender: "Female",
    avatar: "https://robohash.org/aliquamuthic.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Aloysius",
    last_name: "Woltman",
    email: "awoltman37@photobucket.com",
    password: "awoltman37@photobucket.com",
    gender: "Male",
    avatar:
      "https://robohash.org/consequaturhicexercitationem.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Sunny",
    last_name: "Rosingdall",
    email: "srosingdall38@columbia.edu",
    password: "srosingdall38@columbia.edu",
    gender: "Male",
    avatar: "https://robohash.org/assumendaminussit.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Kirsten",
    last_name: "Dran",
    email: "kdran39@youtube.com",
    password: "kdran39@youtube.com",
    gender: "Female",
    avatar: "https://robohash.org/etrationealiquid.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Pepillo",
    last_name: "O'Flynn",
    email: "poflynn3a@ftc.gov",
    password: "poflynn3a@ftc.gov",
    gender: "Male",
    avatar: "https://robohash.org/placeatnatussit.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Britt",
    last_name: "Mostyn",
    email: "bmostyn3b@home.pl",
    password: "bmostyn3b@home.pl",
    gender: "Female",
    avatar: "https://robohash.org/siteamaxime.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Rancell",
    last_name: "Petracchi",
    email: "rpetracchi3c@hubpages.com",
    password: "rpetracchi3c@hubpages.com",
    gender: "Bigender",
    avatar: "https://robohash.org/ullamsaepemollitia.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Angelika",
    last_name: "Thebe",
    email: "athebe3d@biglobe.ne.jp",
    password: "athebe3d@biglobe.ne.jp",
    gender: "Genderqueer",
    avatar: "https://robohash.org/inciduntenimrerum.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Milicent",
    last_name: "Wooffitt",
    email: "mwooffitt3e@eventbrite.com",
    password: "mwooffitt3e@eventbrite.com",
    gender: "Female",
    avatar: "https://robohash.org/utetvoluptatem.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Agneta",
    last_name: "Petett",
    email: "apetett3f@whitehouse.gov",
    password: "apetett3f@whitehouse.gov",
    gender: "Female",
    avatar: "https://robohash.org/etblanditiisaut.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Whitney",
    last_name: "Gulston",
    email: "wgulston3g@slideshare.net",
    password: "wgulston3g@slideshare.net",
    gender: "Male",
    avatar: "https://robohash.org/sitfugitnemo.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Murial",
    last_name: "Axtell",
    email: "maxtell3h@paypal.com",
    password: "maxtell3h@paypal.com",
    gender: "Bigender",
    avatar: "https://robohash.org/doloremimpeditipsam.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Pebrook",
    last_name: "Stoneham",
    email: "pstoneham3i@redcross.org",
    password: "pstoneham3i@redcross.org",
    gender: "Male",
    avatar:
      "https://robohash.org/rerumexercitationemdoloremque.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Cecil",
    last_name: "Varndall",
    email: "cvarndall3j@oracle.com",
    password: "cvarndall3j@oracle.com",
    gender: "Male",
    avatar: "https://robohash.org/velitrerumeligendi.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Brier",
    last_name: "McCrossan",
    email: "bmccrossan3k@rambler.ru",
    password: "bmccrossan3k@rambler.ru",
    gender: "Polygender",
    avatar: "https://robohash.org/autemvoluptatemrerum.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Hannie",
    last_name: "Mishow",
    email: "hmishow3l@wsj.com",
    password: "hmishow3l@wsj.com",
    gender: "Female",
    avatar: "https://robohash.org/quoutaut.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Clair",
    last_name: "Wardale",
    email: "cwardale3m@weibo.com",
    password: "cwardale3m@weibo.com",
    gender: "Female",
    avatar: "https://robohash.org/estundedolores.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Gabriella",
    last_name: "Purcell",
    email: "gpurcell3n@army.mil",
    password: "gpurcell3n@army.mil",
    gender: "Female",
    avatar: "https://robohash.org/veletnon.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Alene",
    last_name: "Toten",
    email: "atoten3o@aboutads.info",
    password: "atoten3o@aboutads.info",
    gender: "Female",
    avatar:
      "https://robohash.org/inciduntprovidentnemo.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Cornela",
    last_name: "Southerill",
    email: "csoutherill3p@deviantart.com",
    password: "csoutherill3p@deviantart.com",
    gender: "Polygender",
    avatar: "https://robohash.org/beataeipsumatque.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Erwin",
    last_name: "MacSkeagan",
    email: "emacskeagan3q@diigo.com",
    password: "emacskeagan3q@diigo.com",
    gender: "Male",
    avatar: "https://robohash.org/etillumest.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Keary",
    last_name: "Phizackarley",
    email: "kphizackarley3r@va.gov",
    password: "kphizackarley3r@va.gov",
    gender: "Male",
    avatar: "https://robohash.org/doloremillumautem.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Rae",
    last_name: "Oleksiak",
    email: "roleksiak3s@hubpages.com",
    password: "roleksiak3s@hubpages.com",
    gender: "Female",
    avatar: "https://robohash.org/remplaceatodit.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Stafford",
    last_name: "Napoleone",
    email: "snapoleone3t@vinaora.com",
    password: "snapoleone3t@vinaora.com",
    gender: "Male",
    avatar:
      "https://robohash.org/veniammolestiaevoluptatibus.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Winfield",
    last_name: "Crawforth",
    email: "wcrawforth3u@skyrock.com",
    password: "wcrawforth3u@skyrock.com",
    gender: "Male",
    avatar:
      "https://robohash.org/ducimusdoloresaliquam.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Hildy",
    last_name: "Witherby",
    email: "hwitherby3v@blinklist.com",
    password: "hwitherby3v@blinklist.com",
    gender: "Female",
    avatar: "https://robohash.org/nobisaperiamet.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Jessamyn",
    last_name: "Forsdyke",
    email: "jforsdyke3w@princeton.edu",
    password: "jforsdyke3w@princeton.edu",
    gender: "Female",
    avatar: "https://robohash.org/etducimusquas.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Osbert",
    last_name: "Pinnegar",
    email: "opinnegar3x@dot.gov",
    password: "opinnegar3x@dot.gov",
    gender: "Non-binary",
    avatar: "https://robohash.org/etveniamrerum.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Lydon",
    last_name: "Radbond",
    email: "lradbond3y@tinyurl.com",
    password: "lradbond3y@tinyurl.com",
    gender: "Male",
    avatar: "https://robohash.org/sedquodexpedita.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Anneliese",
    last_name: "Eldridge",
    email: "aeldridge3z@mtv.com",
    password: "aeldridge3z@mtv.com",
    gender: "Female",
    avatar: "https://robohash.org/aetcorporis.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Northrop",
    last_name: "Skerme",
    email: "nskerme40@baidu.com",
    password: "nskerme40@baidu.com",
    gender: "Male",
    avatar: "https://robohash.org/autemducimusnulla.png?size=50x50&set=set1",
    domain: "Management",
    available: true,
  },
  {
    first_name: "Mart",
    last_name: "Corballis",
    email: "mcorballis41@canalblog.com",
    password: "mcorballis41@canalblog.com",
    gender: "Male",
    avatar: "https://robohash.org/autidculpa.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Marylou",
    last_name: "Pech",
    email: "mpech42@hostgator.com",
    password: "mpech42@hostgator.com",
    gender: "Genderqueer",
    avatar: "https://robohash.org/itaqueestautem.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Gunar",
    last_name: "Balf",
    email: "gbalf43@bigcartel.com",
    password: "gbalf43@bigcartel.com",
    gender: "Male",
    avatar:
      "https://robohash.org/culpapraesentiumomnis.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Charlotta",
    last_name: "Buddington",
    email: "cbuddington44@nytimes.com",
    password: "cbuddington44@nytimes.com",
    gender: "Female",
    avatar: "https://robohash.org/velitoditnon.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Morris",
    last_name: "Waddams",
    email: "mwaddams45@pagesperso-orange.fr",
    password: "mwaddams45@pagesperso-orange.fr",
    gender: "Male",
    avatar: "https://robohash.org/laboriosamautoptio.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Roi",
    last_name: "Povall",
    email: "rpovall46@ow.ly",
    password: "rpovall46@ow.ly",
    gender: "Male",
    avatar: "https://robohash.org/nonnostrumquis.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Shawn",
    last_name: "Swalwell",
    email: "sswalwell47@google.fr",
    password: "sswalwell47@google.fr",
    gender: "Male",
    avatar: "https://robohash.org/consecteturcumqueaut.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Armstrong",
    last_name: "Hysom",
    email: "ahysom48@themeforest.net",
    password: "ahysom48@themeforest.net",
    gender: "Male",
    avatar: "https://robohash.org/doloremeosfugiat.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Dorella",
    last_name: "Auty",
    email: "dauty49@list-manage.com",
    password: "dauty49@list-manage.com",
    gender: "Female",
    avatar: "https://robohash.org/suntuteius.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Rheta",
    last_name: "Hildrew",
    email: "rhildrew4a@amazon.de",
    password: "rhildrew4a@amazon.de",
    gender: "Female",
    avatar: "https://robohash.org/remsuntlabore.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Dietrich",
    last_name: "Gowanlock",
    email: "dgowanlock4b@wp.com",
    password: "dgowanlock4b@wp.com",
    gender: "Male",
    avatar: "https://robohash.org/enimsunteum.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Yetta",
    last_name: "Davey",
    email: "ydavey4c@timesonline.co.uk",
    password: "ydavey4c@timesonline.co.uk",
    gender: "Female",
    avatar:
      "https://robohash.org/voluptatemnonofficiis.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Jordanna",
    last_name: "McAmish",
    email: "jmcamish4d@woothemes.com",
    password: "jmcamish4d@woothemes.com",
    gender: "Female",
    avatar: "https://robohash.org/eateneturenim.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Faydra",
    last_name: "Onslow",
    email: "fonslow4e@theguardian.com",
    password: "fonslow4e@theguardian.com",
    gender: "Agender",
    avatar: "https://robohash.org/illomodiearum.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Kane",
    last_name: "Arlet",
    email: "karlet4f@ftc.gov",
    password: "karlet4f@ftc.gov",
    gender: "Male",
    avatar: "https://robohash.org/pariaturnondolorum.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Carlyle",
    last_name: "Bolver",
    email: "cbolver4g@fda.gov",
    password: "cbolver4g@fda.gov",
    gender: "Male",
    avatar: "https://robohash.org/molestiaemolestiaeet.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Ezra",
    last_name: "Postance",
    email: "epostance4h@intel.com",
    password: "epostance4h@intel.com",
    gender: "Male",
    avatar: "https://robohash.org/ipsaveniamsed.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Leila",
    last_name: "Isaksson",
    email: "lisaksson4i@hao123.com",
    password: "lisaksson4i@hao123.com",
    gender: "Female",
    avatar: "https://robohash.org/facilissedtotam.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Rogers",
    last_name: "Tomkies",
    email: "rtomkies4j@reverbnation.com",
    password: "rtomkies4j@reverbnation.com",
    gender: "Male",
    avatar: "https://robohash.org/namminuserror.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Elianore",
    last_name: "de Zamora",
    email: "edezamora4k@sohu.com",
    password: "edezamora4k@sohu.com",
    gender: "Female",
    avatar: "https://robohash.org/quodsedharum.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Agneta",
    last_name: "Slamaker",
    email: "aslamaker4l@github.io",
    password: "aslamaker4l@github.io",
    gender: "Female",
    avatar: "https://robohash.org/quomolestiasqui.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Marie",
    last_name: "Imms",
    email: "mimms4m@unblog.fr",
    password: "mimms4m@unblog.fr",
    gender: "Female",
    avatar: "https://robohash.org/quoddolorquo.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Kaia",
    last_name: "Measom",
    email: "kmeasom4n@auda.org.au",
    password: "kmeasom4n@auda.org.au",
    gender: "Female",
    avatar: "https://robohash.org/suscipitvoluptatemet.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Alister",
    last_name: "Spehr",
    email: "aspehr4o@thetimes.co.uk",
    password: "aspehr4o@thetimes.co.uk",
    gender: "Male",
    avatar: "https://robohash.org/possimusabiste.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Benedikt",
    last_name: "Stobbe",
    email: "bstobbe4p@pinterest.com",
    password: "bstobbe4p@pinterest.com",
    gender: "Male",
    avatar:
      "https://robohash.org/voluptatumexpeditapraesentium.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Nicky",
    last_name: "Keyson",
    email: "nkeyson4q@prweb.com",
    password: "nkeyson4q@prweb.com",
    gender: "Non-binary",
    avatar: "https://robohash.org/autdoloresquis.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Taylor",
    last_name: "Atyea",
    email: "tatyea4r@spotify.com",
    password: "tatyea4r@spotify.com",
    gender: "Male",
    avatar: "https://robohash.org/porroeostenetur.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Pearl",
    last_name: "Mustarde",
    email: "pmustarde4s@google.de",
    password: "pmustarde4s@google.de",
    gender: "Female",
    avatar:
      "https://robohash.org/consequunturrerumperferendis.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Vivianna",
    last_name: "Kuhl",
    email: "vkuhl4t@godaddy.com",
    password: "vkuhl4t@godaddy.com",
    gender: "Female",
    avatar:
      "https://robohash.org/repudiandaerationeofficia.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Haze",
    last_name: "Sommer",
    email: "hsommer4u@etsy.com",
    password: "hsommer4u@etsy.com",
    gender: "Male",
    avatar:
      "https://robohash.org/adipisciexcepturiipsam.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Patton",
    last_name: "Gearing",
    email: "pgearing4v@usatoday.com",
    password: "pgearing4v@usatoday.com",
    gender: "Male",
    avatar:
      "https://robohash.org/quirepudiandaeaperiam.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Beryle",
    last_name: "Spaight",
    email: "bspaight4w@merriam-webster.com",
    password: "bspaight4w@merriam-webster.com",
    gender: "Female",
    avatar: "https://robohash.org/saepesitdoloremque.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Halette",
    last_name: "Schaumann",
    email: "hschaumann4x@cisco.com",
    password: "hschaumann4x@cisco.com",
    gender: "Female",
    avatar: "https://robohash.org/voluptasaperiamnon.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Melloney",
    last_name: "Comelli",
    email: "mcomelli4y@amazon.de",
    password: "mcomelli4y@amazon.de",
    gender: "Female",
    avatar:
      "https://robohash.org/fugapossimuspraesentium.png?size=50x50&set=set1",
    domain: "Sales",
    available: true,
  },
  {
    first_name: "Sanders",
    last_name: "Ridewood",
    email: "sridewood4z@kickstarter.com",
    password: "sridewood4z@kickstarter.com",
    gender: "Male",
    avatar:
      "https://robohash.org/velitrepellatrepudiandae.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Luelle",
    last_name: "MacAlpin",
    email: "lmacalpin50@huffingtonpost.com",
    password: "lmacalpin50@huffingtonpost.com",
    gender: "Female",
    avatar:
      "https://robohash.org/nostrumveroarchitecto.png?size=50x50&set=set1",
    domain: "IT",
    available: true,
  },
  {
    first_name: "Quill",
    last_name: "Storey",
    email: "qstorey51@wix.com",
    password: "qstorey51@wix.com",
    gender: "Male",
    avatar:
      "https://robohash.org/modirepudiandaeadipisci.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Yalonda",
    last_name: "Burdas",
    email: "yburdas52@epa.gov",
    password: "yburdas52@epa.gov",
    gender: "Female",
    avatar: "https://robohash.org/repellataliquamqui.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Putnam",
    last_name: "Mansour",
    email: "pmansour53@answers.com",
    password: "pmansour53@answers.com",
    gender: "Male",
    avatar: "https://robohash.org/ealiberoqui.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Rooney",
    last_name: "Roderighi",
    email: "rroderighi54@springer.com",
    password: "rroderighi54@springer.com",
    gender: "Male",
    avatar: "https://robohash.org/enimlaborumipsum.png?size=50x50&set=set1",
    domain: "Finance",
    available: false,
  },
  {
    first_name: "Reinaldos",
    last_name: "Shuttleworth",
    email: "rshuttleworth55@alibaba.com",
    password: "rshuttleworth55@alibaba.com",
    gender: "Male",
    avatar: "https://robohash.org/totamquieos.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Stacia",
    last_name: "Curreen",
    email: "scurreen56@unc.edu",
    password: "scurreen56@unc.edu",
    gender: "Female",
    avatar: "https://robohash.org/cupiditatesintomnis.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Pablo",
    last_name: "Di Giacomettino",
    email: "pdigiacomettino57@unblog.fr",
    password: "pdigiacomettino57@unblog.fr",
    gender: "Male",
    avatar:
      "https://robohash.org/accusamusnostrumvoluptatem.png?size=50x50&set=set1",
    domain: "Business Development",
    available: false,
  },
  {
    first_name: "Jacobo",
    last_name: "Duesbury",
    email: "jduesbury58@smugmug.com",
    password: "jduesbury58@smugmug.com",
    gender: "Male",
    avatar: "https://robohash.org/quibusdamsitneque.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Jorey",
    last_name: "Kynan",
    email: "jkynan59@nydailynews.com",
    password: "jkynan59@nydailynews.com",
    gender: "Female",
    avatar: "https://robohash.org/providentdolorsoluta.png?size=50x50&set=set1",
    domain: "Marketing",
    available: true,
  },
  {
    first_name: "Jacinta",
    last_name: "Pedlow",
    email: "jpedlow5a@netlog.com",
    password: "jpedlow5a@netlog.com",
    gender: "Female",
    avatar: "https://robohash.org/nambeataedolores.png?size=50x50&set=set1",
    domain: "IT",
    available: false,
  },
  {
    first_name: "Alf",
    last_name: "Cuss",
    email: "acuss5b@icq.com",
    password: "acuss5b@icq.com",
    gender: "Male",
    avatar: "https://robohash.org/debitissedquos.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: true,
  },
  {
    first_name: "Devin",
    last_name: "Ahmad",
    email: "dahmad5c@springer.com",
    password: "dahmad5c@springer.com",
    gender: "Female",
    avatar: "https://robohash.org/eosvoluptatemdolor.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Dallon",
    last_name: "Stampfer",
    email: "dstampfer5d@flickr.com",
    password: "dstampfer5d@flickr.com",
    gender: "Male",
    avatar: "https://robohash.org/nesciuntnisisint.png?size=50x50&set=set1",
    domain: "Finance",
    available: true,
  },
  {
    first_name: "Yelena",
    last_name: "Fairnie",
    email: "yfairnie5e@yellowpages.com",
    password: "yfairnie5e@yellowpages.com",
    gender: "Female",
    avatar: "https://robohash.org/suntsintaut.png?size=50x50&set=set1",
    domain: "Management",
    available: false,
  },
  {
    first_name: "Duff",
    last_name: "Oxtiby",
    email: "doxtiby5f@tiny.cc",
    password: "doxtiby5f@tiny.cc",
    gender: "Male",
    avatar:
      "https://robohash.org/praesentiumilloasperiores.png?size=50x50&set=set1",
    domain: "Business Development",
    available: true,
  },
  {
    first_name: "Pammie",
    last_name: "Signori",
    email: "psignori5g@webeden.co.uk",
    password: "psignori5g@webeden.co.uk",
    gender: "Genderqueer",
    avatar:
      "https://robohash.org/numquamquibusdamfacere.png?size=50x50&set=set1",
    domain: "Marketing",
    available: false,
  },
  {
    first_name: "Fabian",
    last_name: "Damper",
    email: "fdamper5h@webmd.com",
    password: "fdamper5h@webmd.com",
    gender: "Male",
    avatar: "https://robohash.org/doloresquaeratmagni.png?size=50x50&set=set1",
    domain: "UI Designing",
    available: false,
  },
  {
    first_name: "Ambrosius",
    last_name: "Wendover",
    email: "awendover5i@bbc.co.uk",
    password: "awendover5i@bbc.co.uk",
    gender: "Male",
    avatar: "https://robohash.org/quisquamquiomnis.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
  {
    first_name: "Stavro",
    last_name: "Potkins",
    email: "spotkins5j@admin.ch",
    password: "spotkins5j@admin.ch",
    gender: "Male",
    avatar: "https://robohash.org/velittemporaaut.png?size=50x50&set=set1",
    domain: "Sales",
    available: false,
  },
];

const createUser = () => {
  const result = users.map(async (e) => {
    const hash = await argon2.hash(e.password);
    return await user.create({
      first_name: e.first_name,
      last_name: e.last_name,
      email: e.email,
      password: hash,
      gender: e.gender,
      avatar: e.avatar,
      domain: e.domain,
      available: e.available,
    });
  });

  console.log(result);
};

createUser();
